# -*- coding: utf-8 -*-
"""evaluate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sDuKBD6hO_IkC2-VsmrnWTH8h8wNEGIA
"""

import time
import torch
import torch.nn as nn

device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
loss_func = nn.CrossEntropyLoss().to(device)


def evaluate(model, test_loader, device, loss_func):
    correct, total = 0, 0
    
    start = time.time()
    model.eval()
    with torch.no_grad():

        for image, label in test_loader:
            x = image.to(device)
            y = label.to(device)
            
            output = model.forward(x)
            _, output_index = torch.max(output, 1)

            total += label.size(0)
            correct += (output_index==y).sum().float()
        
    print('Accuracy  : {}'.format(correct / total * 100))

"""- test 파일명으로는 Colab에서의 다른 예약어와 겹쳐 사용 불가"""